### ISSUE TITLE
Send all emails to test account on Dev

### ISSUE THREAD

**Issue by mattheu** [humanmade/hm-mandrill#1]
Currently - you can't send emails in Salty WordPress so you never have to worry that you might accidentally email everyone from your local dev environment. I really like that this just isn't possible.

But - HM Mandrill makes this possible!

Do you think its worth adding functionality to define a test address - and if defined all emails are sent there?

Other options - define a different mandrill account API key for local - but this requires everyone to have an account.

Any thoughts @joehoyle ?

**Comment by joehoyle** [comment]
Hmm, I think we may have added sendmail to the latest Salty WordPress, so you can actually send email, however we do exactly this on marketrealist, send all to a dev email. Would be good to port that over to this plguin.

**Comment by joehoyle** [comment]
Turns out we already have this here: https://github.com/humanmade/hm-mandrill/blob/master/inc/class-hm-mandrill.php#L10
