### ISSUE TITLE
Plain text emails - line breaks broken.

### ISSUE THREAD

**Issue by mattheu** [humanmade/hm-mandrill#2]
If you install this plugin on a standard WP site, all line breaks are stripped from emails.

I think that the reason for this is that you can pass the message to the API using either the `html` or `text` params depending of the format of your message. The plugin always sends as HTML.

The only way to really test for an HTML message is to look for a the `content-type=text/html` header - and default to `text/plain` - and send either HTML or Text depending on this value.

However... this will break any current sites using the plugin that aren't passing the `text/html` header to the wp_mail function call.

I'm not sure what the best course of action is here. Currently it breaks default WordPress emails.

**Comment by mattheu** [comment]
I've reverted to sending by SMTP for now

**Comment by joehoyle** [comment]
Oh yeah we need to just support the header
